version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      # Exclude node_modules from volume mapping
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Add this for better file watching
    # Enable container to restart if it crashes
    restart: unless-stopped
