/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nelib (https://sketchfab.com/Nelib)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/wuhu-island-wii-sports-resort-68d83db076c944fdb5e1273f95b4fc7d
Title: Wuhu Island - Wii Sports Resort
*/
import islandurl from '/island.glb?url'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';


type GLTFResult = {
    nodes: {
      Object_3: THREE.Mesh;
      Object_4: THREE.Mesh;
      Object_5: THREE.Mesh;
      Object_6: THREE.Mesh;
      Object_7: THREE.Mesh;
      Object_8: THREE.Mesh;
      Object_9: THREE.Mesh;
      Object_10: THREE.Mesh;
      Object_11: THREE.Mesh;
      Object_12: THREE.Mesh;
      Object_13: THREE.Mesh;
      Object_14: THREE.Mesh;
      Object_15: THREE.Mesh;
      Object_16: THREE.Mesh;
      Object_17: THREE.Mesh;
      Object_18: THREE.Mesh;
      Object_19: THREE.Mesh;
      Object_20: THREE.Mesh;
      Object_21: THREE.Mesh;
      Object_22: THREE.Mesh;
      Object_23: THREE.Mesh;
      Object_24: THREE.Mesh;
      Object_25: THREE.Mesh;
      Object_26: THREE.Mesh;
      Object_27: THREE.Mesh;
      Object_28: THREE.Mesh;
      Object_29: THREE.Mesh;
      Object_30: THREE.Mesh;
      Object_31: THREE.Mesh;
      Object_32: THREE.Mesh;
      Object_33: THREE.Mesh;
      Object_34: THREE.Mesh;
      Object_35: THREE.Mesh;
      Object_36: THREE.Mesh;
      Object_37: THREE.Mesh;
      Object_38: THREE.Mesh;
      Object_39: THREE.Mesh;
      Object_40: THREE.Mesh;
      Object_41: THREE.Mesh;
      Object_42: THREE.Mesh;
      Object_43: THREE.Mesh;
      Object_44: THREE.Mesh;
      Object_45: THREE.Mesh;
      Object_46: THREE.Mesh;
      Object_47: THREE.Mesh;
      Object_48: THREE.Mesh;
    };
    materials: {
      Material_179: THREE.MeshStandardMaterial;
      Material_179_0: THREE.MeshStandardMaterial;
      Material_179_1: THREE.MeshStandardMaterial;
      Material_179_2: THREE.MeshStandardMaterial;
      Material_179_3: THREE.MeshStandardMaterial;
      Material_179_4: THREE.MeshStandardMaterial;
      Material_179_5: THREE.MeshStandardMaterial;
      Material_179_6: THREE.MeshStandardMaterial;
      Material_179_7: THREE.MeshStandardMaterial;
      Material_179_8: THREE.MeshStandardMaterial;
      Material_179_9: THREE.MeshStandardMaterial;
      Material_179_10: THREE.MeshStandardMaterial;
      Material_179_11: THREE.MeshStandardMaterial;
      Material_179_12: THREE.MeshStandardMaterial;
      Material_179_13: THREE.MeshStandardMaterial;
      Material_179_14: THREE.MeshStandardMaterial;
      Material_179_15: THREE.MeshStandardMaterial;
      Material_179_16: THREE.MeshStandardMaterial;
      Material_179_17: THREE.MeshStandardMaterial;
      Material_179_18: THREE.MeshStandardMaterial;
      Material_179_19: THREE.MeshStandardMaterial;
      Material_179_20: THREE.MeshStandardMaterial;
      Material_179_21: THREE.MeshStandardMaterial;
      Material_179_22: THREE.MeshStandardMaterial;
      Material_179_23: THREE.MeshStandardMaterial;
      Material_179_24: THREE.MeshStandardMaterial;
      Material_179_25: THREE.MeshStandardMaterial;
      Material_179_26: THREE.MeshStandardMaterial;
      Material_179_27: THREE.MeshStandardMaterial;
      Material_179_28: THREE.MeshStandardMaterial;
      Material_179_29: THREE.MeshStandardMaterial;
      Material_179_30: THREE.MeshStandardMaterial;
      Material_179_31: THREE.MeshStandardMaterial;
      Material_179_32: THREE.MeshStandardMaterial;
      Material_179_33: THREE.MeshStandardMaterial;
      Material_179_34: THREE.MeshStandardMaterial;
      Material_179_35: THREE.MeshStandardMaterial;
      Material_179_36: THREE.MeshStandardMaterial;
      Material_179_37: THREE.MeshStandardMaterial;
      Material_179_38: THREE.MeshStandardMaterial;
      Material_179_39: THREE.MeshStandardMaterial;
      Material_179_40: THREE.MeshStandardMaterial;
      Material_179_41: THREE.MeshStandardMaterial;
      Material_179_42: THREE.MeshStandardMaterial;
      Material_179_43: THREE.MeshStandardMaterial;
    };
  };

export function Island(props: any) {
  const { nodes, materials } = useGLTF(islandurl) as unknown as GLTFResult;
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
        <group position={[-1139526.375, -1139353.5, -2169.607]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.Material_179}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Material_179_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.Material_179_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Material_179_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.Material_179_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.Material_179_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.Material_179_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.Material_179_6}
          />
          {/* chutte grande cascase d'eau */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.Material_179_7}
          /> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.Material_179_8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.Material_179_9}
          />
          {/* Vagues plages */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.Material_179_10}
          /> */}
          {/* petits reflets d'eaux */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            // material={materials.Material_179_11}
          /> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Material_179_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.Material_179_13}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.Material_179_14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.Material_179_15}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.Material_179_16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials.Material_179_17}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.Material_179_17}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials.Material_179_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.Material_179_19}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials.Material_179_20}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.Material_179_21}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.Material_179_22}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.Material_179_23}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials.Material_179_24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.Material_179_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.Material_179_26}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.Material_179_27}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.Material_179_28}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.Material_179_29}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.Material_179_30}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.Material_179_31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials.Material_179_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.Material_179_33}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials.Material_179_34}
          />
          {/* eau tout autour */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            // material={materials.Material_179_35}
          /> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.Material_179_36}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.Material_179_37}
          />
          {/* grande cascase d'eau */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials.Material_179_38}
          /> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials.Material_179_39}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials.Material_179_40}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials.Material_179_41}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.Material_179_42}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.Material_179_43}
          />
        </group>
      </group>
    </group>
  )
}


