name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20' # Adjust Node.js version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Upload static site files as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist # Replace with the directory containing your build files

  # Deploy static files to GitHub Pages
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
